### find person by id
GET http://localhost:8080/person/1
# Accept: application/json

### find all people
GET http://localhost:8080/person

### find vehicle by id
GET http://localhost:8080/vehicle/2

### find all vehicles
GET http://localhost:8080/vehicle

### find all rentals
GET http://localhost:8080/rentals

